# -*- coding: utf-8 -*-
"""Despliegue_Final_Minería.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiKWZs1K0_Nbn7p9fBeNkHZg9VAmX2d4

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el pipeline con el modelo
import pickle
filename = 'pipeline_modelo.pkl'
pipeline = pickle.load(open(filename, 'rb'))
pipeline

#Cargamos los datos futuros
data = pd.read_excel("datos_futuros.xlsx")
data.head()

import streamlit as st
import pandas as pd
import numpy as np
import joblib

st.set_page_config(page_title='Predicción de energía', layout='centered')

st.title(' Predicción de rendimiento energético del sistema')

st.markdown("""
Ajusta los valores de las variables meteorológicas y de capacidad para estimar la **producción esperada** o la **variable objetivo** según tu modelo entrenado.
""")

# --- Cargar el pipeline entrenado ---
@st.cache_resource
def load_pipeline(path='final_model_pipeline.joblib'):
    return joblib.load(path)

pipeline = load_pipeline('final_model_pipeline.joblib')

# --- Definir columnas ---
numeric_cols = [
    'Outdoor Temperature (Â°C)_max', 'Outdoor Temperature (Â°C)_min',
    'Feels Like (Â°C)_max', 'Feels Like (Â°C)_min',
    'Dew Point (Â°C)_max', 'Dew Point (Â°C)_min',
    'Wind Speed (m/sec)_max', 'Wind Gust (m/sec)_max',
    'Max Daily Gust (m/sec)_max', 'Wind Direction (Â°)_max',
    'Wind Direction (Â°)_min', 'Rain Rate (mm/hr)_max',
    'Daily Rain (mm)_max', 'Weekly Rain (mm)_max', 'Weekly Rain (mm)_min',
    'Yearly Rain (mm)_max', 'Yearly Rain (mm)_min', 'Humidity (%)_min',
    'Ultra-Violet Radiation Index_max', 'Solar Radiation (W/m^2)_max',
    'Indoor Temperature (Â°C)_max', 'Indoor Temperature (Â°C)_min',
    'Indoor Humidity (%)_max', 'Indoor Humidity (%)_min',
    'Avg Wind Direction (10 mins) (Â°)_min'
]

capacity_cols = ['capacity_45kw', 'capacity_52kw']

# --- Crear controles de entrada ---
st.subheader(" Variables Meteorológicas")
user_inputs = {}
cols = st.columns(3)
for i, col in enumerate(numeric_cols):
    with cols[i % 3]:
        user_inputs[col] = st.number_input(f"{col}", value=0.0, step=0.1, format="%.2f")

st.subheader("Capacidad del sistema")
capacity_45 = st.checkbox("Capacidad 45kW", value=False)
capacity_52 = st.checkbox("Capacidad 52kW", value=False)

user_inputs['capacity_45kw'] = int(capacity_45)
user_inputs['capacity_52kw'] = int(capacity_52)

# --- Crear DataFrame para predicción ---
data = pd.DataFrame([user_inputs])

# --- Predicción ---
if st.button(' Predecir'):
    pred = pipeline.predict(data)[0]
    st.success(f'Predicción del modelo: **{pred:.2f}**')

st.markdown("---")
st.caption("pruebas del modelo final.")

#Hacemos la predicción con el RF
Y_pred = pipeline.predict(data)
print(Y_pred)

data['energyproducedtoday']=Y_pred
data