# -*- coding: utf-8 -*-
"""Despliegue_Final_Minería.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BiKWZs1K0_Nbn7p9fBeNkHZg9VAmX2d4

# Despliegue

- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Cargamos el pipeline con el modelo
import pickle
filename = 'pipeline_modelo.pkl'
pipeline = pickle.load(open(filename, 'rb'))
pipeline

#Cargamos los datos futuros
data = pd.read_excel("datos_futuros.xlsx")
data.head()

import streamlit as st
import pandas as pd
import joblib

# Cargar el pipeline
model = joblib.load("pipeline_modelo.pkl")

st.title(" Predicción de Energía Solar — Despliegue de Modelo")

st.markdown("""
Este sistema permite cargar un archivo Excel con variables meteorológicas
para predecir la **capacidad energética esperada** según el modelo entrenado.
""")

# Subida de archivo Excel
uploaded_file = st.file_uploader(" Sube tu archivo Excel (.xlsx) con los datos futuros", type=["xlsx"])

if uploaded_file is not None:
    try:
        data = pd.read_excel(uploaded_file)
        st.success("Archivo cargado exitosamente ")

        st.write("### Vista previa de los datos:")
        st.dataframe(data.head())

        # Realizar predicciones
        preds = model.predict(data)
        data["Predicción (kW)"] = preds

        st.write("### Resultados de la predicción:")
        st.dataframe(data)

        # Exportar resultados
        output_path = "predicciones_resultado.xlsx"
        data.to_excel(output_path, index=False)

        with open(output_path, "rb") as f:
            st.download_button(
                label=" Descargar archivo con predicciones",
                data=f,
                file_name="predicciones_resultado.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

    except Exception as e:
        st.error(f" Error al procesar el archivo: {e}")

else:
    st.info("Por favor, sube un archivo Excel para generar predicciones.")

#Hacemos la predicción con el RF
Y_pred = pipeline.predict(data)
print(Y_pred)

data['energyproducedtoday']=Y_pred
data